services:
  postgres:
    image: postgres:latest
    container_name: device_backendDB
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5555:5432

  service:
    image: device_backend:latest
    container_name: device_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - 8000:8080
    depends_on:
      - postgres